Repository raven-actions/actionlint, pull requests merged in 2023-11, with the labels that each got.

#15 Fix debian install shellcheck
  action.yml
Labels: bug, enhancement

#16 Make yamllint happy
  .yamllint
  action.yml
Labels: enhancement

#19 fix: user flags parser
  action.yml
Labels: bug
